# ICONV_FOUND - system has Iconv 
# ICONV_INCLUDE_DIR - the Iconv include directory 
# ICONV_LIBRARIES - Link these to use Iconv 

FIND_PATH(ICONV_INCLUDE_DIR iconv.h) 
FIND_LIBRARY(ICONV_LIBRARIES NAMES iconv libiconv libiconv-2 c)
 
IF(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES) 
	 SET(ICONV_FOUND TRUE) 
ENDIF(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES) 
