set(BOOST_CMAKE_ARGS ${COMMON_CMAKE_ARGS}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    -DANDROID_NATIVE_API_LEVEL=${ANDROID_NATIVE_API_LEVEL}
)

set(BOOST_PATCH_DIR ${CMAKE_CURRENT_SOURCE_DIR}/patch)

set(PATCH_CMD ${CMAKE_COMMAND} -E copy_directory "${BOOST_PATCH_DIR}/android" "<SOURCE_DIR>/")

ExternalProject_Add(
    boost
    DEPENDS zlib libiconv
    URL ${CACHED_URL}
    URL_HASH SHA256=${BOOST_HASHSUM}
    DOWNLOAD_DIR ${ARCHIVE_DIR}
    BUILD_IN_SOURCE 1
    PATCH_COMMAND ${PATCH_CMD}
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    CMAKE_ARGS ${BOOST_CMAKE_ARGS}
)
