# Fix hardcoded paths in VTK cmake files
message("Fix VTK CMake export files...")

file(GLOB_RECURSE VTK_CMAKE_FILES "${CMAKE_INSTALL_PREFIX}/lib/cmake/vtk*/*.cmake")

foreach(CMAKE_FILE ${VTK_CMAKE_FILES})
    file(STRINGS ${CMAKE_FILE} CMAKE_FILE_CONTENT NEWLINE_CONSUME)
    string(REGEX REPLACE "${CMAKE_INSTALL_PREFIX}" "\${VTK_INSTALL_PREFIX}" CMAKE_FILE_CONTENT_MODIFIED "${CMAKE_FILE_CONTENT}")
    file(WRITE ${CMAKE_FILE} ${CMAKE_FILE_CONTENT_MODIFIED})
endforeach()

# Fix hardcoded paths in Dcmtk cmake files
message("Fix DCMTK CMake export files...")

file(GLOB_RECURSE DCMTK_CMAKE_FILES "${CMAKE_INSTALL_PREFIX}/lib/cmake/dcmtk/*.cmake")

foreach(CMAKE_FILE ${DCMTK_CMAKE_FILES})
    file(STRINGS ${CMAKE_FILE} CMAKE_FILE_CONTENT NEWLINE_CONSUME)
    string(REGEX REPLACE "${CMAKE_INSTALL_PREFIX}" "\${_IMPORT_PREFIX}" CMAKE_FILE_CONTENT_MODIFIED "${CMAKE_FILE_CONTENT}")
    file(WRITE ${CMAKE_FILE} ${CMAKE_FILE_CONTENT_MODIFIED})
endforeach()

# Fix hardcoded paths in PCL cmake files
message("Fix PCL CMake export files...")

file(GLOB_RECURSE PCL_CMAKE_FILES "${CMAKE_INSTALL_PREFIX}/share/pcl*/*.cmake")

foreach(CMAKE_FILE ${PCL_CMAKE_FILES})
    file(STRINGS ${CMAKE_FILE} CMAKE_FILE_CONTENT NEWLINE_CONSUME)
    string(REGEX REPLACE "${CMAKE_INSTALL_PREFIX}" "\${PCL_ROOT}" CMAKE_FILE_CONTENT_MODIFIED "${CMAKE_FILE_CONTENT}")
    file(WRITE ${CMAKE_FILE} ${CMAKE_FILE_CONTENT_MODIFIED})
endforeach()

